wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.5
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682460685.181338
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 48
      - 49
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.7.5
      5: 0.15.0
      6: 4.28.1
      8:
      - 5
